FROM python:3.7

ENV PYTHONUNBUFFERED 1

# Install a specific version of docker
RUN curl -sSL https://get.docker.com/ | sed 's/docker-ce/docker-ce=18.03.0~ce-0~debian/' | sh


ADD requirements.worker.txt .
RUN pip install -r requirements.worker.txt

WORKDIR /app
